import type { AuditEvent, TelemetryReading, PassportAttribute } from '@/types';
import { getAttributesByPassportId } from '@/data/passportAttributes';

// ============================================================
// EXPORT SERVICE
// ============================================================
// Provides export functionality for passport JSON, audit CSV, and
// telemetry CSV. All exports include metadata: timestamp,
// generated-by, and demo disclaimer.
//
// @validates FR-013 — Export Reports
// ============================================================

/** Metadata included in every export */
interface ExportMetadata {
  exportedAt: string;
  generatedBy: string;
  disclaimer: string;
}

function getExportMetadata(): ExportMetadata {
  return {
    exportedAt: new Date().toISOString(),
    generatedBy: 'Battery Passport Platform Demo',
    disclaimer: 'Demo data - synthetic values for demonstration only',
  };
}

// ============================================================
// DOWNLOAD HELPER
// ============================================================

/**
 * Creates a Blob and triggers a file download in the browser.
 */
export function downloadBlob(
  content: string,
  filename: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();

  URL.revokeObjectURL(url);
}

// ============================================================
// JSON PASSPORT EXPORT
// ============================================================

interface PassportExportJSON {
  metadata: ExportMetadata;
  passportId: string;
  attributes: PassportAttribute[];
  summary: {
    totalAttributes: number;
    verified: number;
    provided: number;
    draft: number;
    missing: number;
    expired: number;
  };
}

/**
 * Exports all passport attributes for a given passport ID as structured JSON.
 * Includes metadata (timestamp, generator, disclaimer) and attribute summary.
 */
export function exportPassportJSON(passportId: string): void {
  const attributes = getAttributesByPassportId(passportId);

  const summary = {
    totalAttributes: attributes.length,
    verified: attributes.filter((a) => a.status === 'verified').length,
    provided: attributes.filter((a) => a.status === 'provided').length,
    draft: attributes.filter((a) => a.status === 'draft').length,
    missing: attributes.filter((a) => a.status === 'missing').length,
    expired: attributes.filter((a) => a.status === 'expired').length,
  };

  const exportData: PassportExportJSON = {
    metadata: getExportMetadata(),
    passportId,
    attributes,
    summary,
  };

  const json = JSON.stringify(exportData, null, 2);
  const filename = `passport-${passportId}-${new Date().toISOString().slice(0, 10)}.json`;

  downloadBlob(json, filename, 'application/json');
}

// ============================================================
// CSV AUDIT TRAIL EXPORT
// ============================================================

/**
 * Exports audit events as CSV with metadata header rows.
 * Moved from AuditTrailPage to shared service for reuse.
 */
export function exportAuditCSV(events: AuditEvent[]): void {
  const metadata = getExportMetadata();

  const metadataRows = [
    `# Exported At: ${metadata.exportedAt}`,
    `# Generated By: ${metadata.generatedBy}`,
    `# Disclaimer: ${metadata.disclaimer}`,
    '',
  ];

  const headers = [
    'Audit Event ID',
    'Timestamp',
    'Actor',
    'Actor Role',
    'Action',
    'Entity Type',
    'Entity ID',
    'Reason',
    'Trace ID',
    'Verification Reference',
    'Source Device',
  ];

  const rows = events.map((e) => [
    e.auditEventId,
    e.timestamp,
    e.actor,
    e.actorRole,
    e.action,
    e.entityType,
    e.entityId,
    `"${e.reason.replace(/"/g, '""')}"`,
    e.traceId,
    e.verificationReference ?? '',
    e.sourceDevice ?? '',
  ]);

  const csv = [
    ...metadataRows,
    headers.join(','),
    ...rows.map((r) => r.join(',')),
  ].join('\n');

  const filename = `audit-trail-export-${new Date().toISOString().slice(0, 10)}.csv`;

  downloadBlob(csv, filename, 'text/csv');
}

// ============================================================
// CSV TELEMETRY SUMMARY EXPORT
// ============================================================

/**
 * Exports telemetry readings as CSV summary with metadata header rows.
 */
export function exportTelemetryCSV(
  readings: TelemetryReading[],
  assetId: string
): void {
  const metadata = getExportMetadata();

  const metadataRows = [
    `# Asset ID: ${assetId}`,
    `# Exported At: ${metadata.exportedAt}`,
    `# Generated By: ${metadata.generatedBy}`,
    `# Disclaimer: ${metadata.disclaimer}`,
    `# Total Readings: ${readings.length}`,
    '',
  ];

  const headers = [
    'Timestamp',
    'SoC (%)',
    'SoH (%)',
    'Equivalent Full Cycles',
    'Energy Charged (kWh)',
    'Energy Discharged (kWh)',
    'Avg Module Temp (°C)',
    'Max Module Temp (°C)',
    'Min Module Temp (°C)',
    'Thermal Gradient (°C)',
    'Round-Trip Efficiency (%)',
    'Availability (%)',
    'Active Alarms',
    'Connectivity Status',
  ];

  const rows = readings.map((r) => [
    r.timestamp,
    r.socPct.toFixed(1),
    r.sohPct.toFixed(2),
    r.equivalentFullCycles.toString(),
    r.energyChargedKWh.toFixed(1),
    r.energyDischargedKWh.toFixed(1),
    r.avgModuleTempC.toFixed(1),
    r.maxModuleTempC.toFixed(1),
    r.minModuleTempC.toFixed(1),
    r.thermalGradientC.toFixed(1),
    r.rollingRoundTripEfficiencyPct.toFixed(1),
    r.availabilityPct.toFixed(2),
    r.activeAlarms.length > 0
      ? `"${r.activeAlarms.map((a) => a.message).join('; ')}"` 
      : '0',
    r.connectivityStatus,
  ]);

  const csv = [
    ...metadataRows,
    headers.join(','),
    ...rows.map((r) => r.join(',')),
  ].join('\n');

  const filename = `telemetry-${assetId}-${new Date().toISOString().slice(0, 10)}.csv`;

  downloadBlob(csv, filename, 'text/csv');
}
